# Site settings
# Enter your own credentials here
title: "MIC-Tungsten-Nanowires"
name: Jason Allen
name2: David Zhao
email: jallen30@gatech.edu
email2: yzhao314@gmail.com
description: >
  This site is dedicated to work on extracting process-structure linkages for the
  electrochemical evolution of tungsten-oxide-hydrate layers on a tungsten wire surface.
baseurl: "/MIC-Tungsten-Nanowires" # replace ``/research-pages`` with the name of the parents repository
url: "materials-informatics-class-fall2014.github.io # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: jallen30gt

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: jallen30gt
  user2: yzhao314 
  repo: MIC-Tungsten-Nanowires
  # Branch hosting Github pages
  branch: gh-pages
