# Site settings
# Enter your own credentials here
title: "MIC-Tungsten-Nanowires"
email: jallen30@gatech.edu
description: >
  Tell us about your site
baseurl: "/MIC-Tungsten-Nanowires" # replace ``/research-pages`` with the name of the parents repository
url: "jallen30gt.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: jallen30gt

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: jallen30gt
  repo: MIC-Tungsten-Nanowires
  # Branch hosting Github pages
  branch: gh-pages
